from pycipher import ADFGVX
a = ADFGVX('agmsy45bhntz06ciouv17djpqw28eklrx39f','uniqlo')
b = a.decipher('AFFAVDAADFFDFDFFFDXDGFDFDFVFDAXVVFVXVGVDVVGXXAVGFGXGGVDFFVVVFDDVAVVGVVFAVFFVFGVGVDVFVAVXVVDGXAVG')

print(b)

